#!/usr/bin/python3 -W ignore
# ******************************************************************************
# Copyright (c) 2020-2023, Virtuozzo International GmbH.
# This source code is distributed under MIT software license.
# ******************************************************************************
import sys
import cloudblue_connector.runners as runners
from getpass import getpass
import argparse
parser = argparse.ArgumentParser(description="Password Encryption utility for cloudblue connector")

parser.add_argument("--set-cloudblue-token", dest="set_cb", action='store_true')
parser.add_argument("--set-pp-password", dest="set_pp", action='store_true')

if len(sys.argv) == 1:
    parser.print_help()

args = parser.parse_args()

if args.set_cb or (not args.set_cb and not args.set_pp):
    token = getpass(prompt='Input CloudBlue token: ')
    runners.set_cloudblue_token(token)

if args.set_pp or (not args.set_cb and not args.set_pp):
    passwd = getpass(prompt='Input PowerPanel password: ')
    runners.set_pp_password(passwd)